// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClIXf-kDhdde2xhQH0iG1DOb00gwKN6lI',
    appId: '1:110642784753:web:451a1dccbcf052b89a3c50',
    messagingSenderId: '110642784753',
    projectId: 'weather-app-dc147',
    authDomain: 'weather-app-dc147.firebaseapp.com',
    storageBucket: 'weather-app-dc147.firebasestorage.app',
    measurementId: 'G-GTBEX1FSE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUdX0alh8GmdtckvzY6hTN9cOaiLzGcNs',
    appId: '1:110642784753:android:3573bafb7ac44d139a3c50',
    messagingSenderId: '110642784753',
    projectId: 'weather-app-dc147',
    storageBucket: 'weather-app-dc147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzLz6OroqzVd3BX6LEz6qNlXV-NDDs4Uk',
    appId: '1:110642784753:ios:1babee18a7be92239a3c50',
    messagingSenderId: '110642784753',
    projectId: 'weather-app-dc147',
    storageBucket: 'weather-app-dc147.firebasestorage.app',
    iosBundleId: 'com.example.countryWeatherExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzLz6OroqzVd3BX6LEz6qNlXV-NDDs4Uk',
    appId: '1:110642784753:ios:1babee18a7be92239a3c50',
    messagingSenderId: '110642784753',
    projectId: 'weather-app-dc147',
    storageBucket: 'weather-app-dc147.firebasestorage.app',
    iosBundleId: 'com.example.countryWeatherExplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClIXf-kDhdde2xhQH0iG1DOb00gwKN6lI',
    appId: '1:110642784753:web:4598632b442900e39a3c50',
    messagingSenderId: '110642784753',
    projectId: 'weather-app-dc147',
    authDomain: 'weather-app-dc147.firebaseapp.com',
    storageBucket: 'weather-app-dc147.firebasestorage.app',
    measurementId: 'G-K65FKZ8ZWF',
  );
}
